/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.employee.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Department service. Represents a row in the &quot;EMPLOYEE_Department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.employee.model.impl.DepartmentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.employee.model.impl.DepartmentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Department
 * @generated
 */
@ProviderType
public interface DepartmentModel extends BaseModel<Department> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a department model instance should use the {@link Department} interface instead.
	 */

	/**
	 * Returns the primary key of this department.
	 *
	 * @return the primary key of this department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this department.
	 *
	 * @param primaryKey the primary key of this department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this department.
	 *
	 * @return the uuid of this department
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this department.
	 *
	 * @param uuid the uuid of this department
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the dep ID of this department.
	 *
	 * @return the dep ID of this department
	 */
	public long getDepId();

	/**
	 * Sets the dep ID of this department.
	 *
	 * @param depId the dep ID of this department
	 */
	public void setDepId(long depId);

	/**
	 * Returns the dep name of this department.
	 *
	 * @return the dep name of this department
	 */
	@AutoEscape
	public String getDepName();

	/**
	 * Sets the dep name of this department.
	 *
	 * @param depName the dep name of this department
	 */
	public void setDepName(String depName);

	/**
	 * Returns the dep no of this department.
	 *
	 * @return the dep no of this department
	 */
	@AutoEscape
	public String getDepNo();

	/**
	 * Sets the dep no of this department.
	 *
	 * @param depNo the dep no of this department
	 */
	public void setDepNo(String depNo);

	/**
	 * Returns the dep address of this department.
	 *
	 * @return the dep address of this department
	 */
	@AutoEscape
	public String getDepAddress();

	/**
	 * Sets the dep address of this department.
	 *
	 * @param depAddress the dep address of this department
	 */
	public void setDepAddress(String depAddress);

	@Override
	public Department cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}