/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.custom.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MyEntity service. Represents a row in the &quot;CUSTOM_MyEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.custom.model.impl.MyEntityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.custom.model.impl.MyEntityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MyEntity
 * @generated
 */
@ProviderType
public interface MyEntityModel extends BaseModel<MyEntity> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a my entity model instance should use the {@link MyEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this my entity.
	 *
	 * @return the primary key of this my entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this my entity.
	 *
	 * @param primaryKey the primary key of this my entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this my entity.
	 *
	 * @return the ID of this my entity
	 */
	public long getId();

	/**
	 * Sets the ID of this my entity.
	 *
	 * @param id the ID of this my entity
	 */
	public void setId(long id);

	/**
	 * Returns the name of this my entity.
	 *
	 * @return the name of this my entity
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this my entity.
	 *
	 * @param name the name of this my entity
	 */
	public void setName(String name);

	/**
	 * Returns the description of this my entity.
	 *
	 * @return the description of this my entity
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this my entity.
	 *
	 * @param description the description of this my entity
	 */
	public void setDescription(String description);

	@Override
	public MyEntity cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}